CREATE TABLE D_EMPLOYEE_ORA03 (
    EMPLOYEE_CD	 		    NUMBER(6),
	EMPLOYEE_NAME	 		NVARCHAR2(200),
	EMPLOYEE_EMAIL	 		NVARCHAR2(50),
	EMPLOYEE_PHONE_NUMBER	NVARCHAR2(200),
	HIRE_DATE			    DATE,
	LAST_DATE			    NVARCHAR2(50),
	JOB_TITLE	 		    NVARCHAR2(35),
	EMPLOYEE_COMMISSION		NUMBER(2,2),
	MANAGER_CD			    NUMBER(6),
	MANAGER_NAME			NVARCHAR2(200),
	ETL_DATE			    TIMESTAMP(6),
	ETL_LAST_UPDATE			TIMESTAMP(6)
);
/
CREATE TABLE  D_DEPARTMENT_ORA03 
(   DEPARTMENT_CD	 		NUMBER(4),
	DEPARTMENT_NAME	 		NVARCHAR2(100),
	STREET_ADDRESS	 		NVARCHAR2(30), 
	POSTAL_CODE	 		    NVARCHAR2(12),
	CITY				    NVARCHAR2(30),
	STATE_PROVINCE	 		NVARCHAR2(25),
	COUNTRY_NAME			NVARCHAR2(40),
	REGION_NAME_EN			NVARCHAR2(25),
	REGION_NAME_TH			NVARCHAR2(25),
	ETL_DATE			    TIMESTAMP(6),
	ETL_LAST_UPDATE			TIMESTAMP(6)
);
/
CREATE TABLE F_SALARY_ORA03(
    SEQ           			NUMBER(10),
    YEAR_CD			        NUMBER(4),
    MONTH_CD			    NUMBER(6),
  	EMPLOYEE_CD             NUMBER(6),
  	JOB_CD           		NVARCHAR2(20),
  	DEPARTMENT_CD           NUMBER(4),
  	EMPLOYEE_SALARY        	NUMBER(8,2),
  	MAX_JOB_SALARY         	NUMBER(6,0),
  	MIN_JOB_SALARY     		NUMBER(6,0),
    MANAGER_SALARY		    NUMBER(8,2),
  	JOB_SALARY_RANKING 		NUMBER(2),
  	ETL_DATE           		TIMESTAMP(6),
  	ETL_LAST_UPDATE    		TIMESTAMP(6)
);
/